# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: Test

on:
  pull_request:
    branches: [ 'main', 'release-*' ]
  push:
    branches: [ 'main', 'release-*' ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code onto GOPATH
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3

    # https://github.com/mvdan/github-actions-golang#how-do-i-set-up-caching-between-builds
    - uses: actions/cache@a7c34adf76222e77931dedbf4a45b2e4648ced19 # v3
      with:
        # In order:
        # * Module download cache
        # * Build cache (Linux)
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Set up Go
      uses: actions/setup-go@268d8c0ca0432bb2cf416faae41297df9d262d7f # v3
      with:
        go-version-file: './go.mod'
        check-latest: true

    - run: |
        # Exclude running unit tests against third_party repos.
        go test -race $(go list ./... | grep -v third_party/)
