# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: Test

on:
  pull_request:
    branches: [ 'main', 'release-*' ]
  push:
    branches: [ 'main', 'release-*' ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code onto GOPATH
      uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3

    # https://github.com/mvdan/github-actions-golang#how-do-i-set-up-caching-between-builds
    - uses: actions/cache@56461b9eb0f8438fd15c7a9968e3c9ebb18ceff1 # v3
      with:
        # In order:
        # * Module download cache
        # * Build cache (Linux)
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Set up Go
      uses: actions/setup-go@d0a58c1c4d2b25278816e339b944508c875f3613 # v3
      with:
        go-version-file: './go.mod'
        check-latest: true

    - run: |
        # Exclude running unit tests against third_party repos.
        go test -race $(go list ./... | grep -v third_party/)
