# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: Test

on:
  pull_request:
    branches: [ 'main', 'release-*' ]
  push:
    branches: [ 'main', 'release-*' ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code onto GOPATH
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3

    # https://github.com/mvdan/github-actions-golang#how-do-i-set-up-caching-between-builds
    - uses: actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7 # v3
      with:
        # In order:
        # * Module download cache
        # * Build cache (Linux)
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Set up Go
      uses: actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f # v3
      with:
        go-version-file: './go.mod'
        check-latest: true

    - run: |
        # Exclude running unit tests against third_party repos.
        go test -race $(go list ./... | grep -v third_party/)
